services:

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    depends_on:
      backend:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

    env_file:
      - ${COMPOSE_ENV_FILE:-.env}

    environment:
      PORT: 4000
      MONGO_URI: mongodb://eventsync:eventsync_password@mongodb:27017/eventsync?authSource=admin

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/api/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s

    depends_on:
      mongodb:
        condition: service_healthy


  mongodb:
    image: mongo:8

    environment:
      MONGO_INITDB_ROOT_USERNAME: eventsync
      MONGO_INITDB_ROOT_PASSWORD: eventsync_password

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
