input {
  beats {
    port => 5044
  }
}

filter {
  http {
    id => "eventsync_adaptive_parser"

    url => "http://eventsync-adaptive-parser:8000/v1/parse"
    verb => "POST"

    headers => {
      "Content-Type" => "application/json"
    }

    body => {
      "message" => "%{[message]}"
    }

    body_format => "json"
    target_body => "[adaptive_parser]"

    connect_timeout => 3
    socket_timeout => 10
    automatic_retries => 0
  }
}

output {
  elasticsearch {
    hosts => ["http://eventsync-elasticsearch:9200"]
    index => "eventsync-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
