input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    add_field => {
      "environment" => "dev"
      "project" => "EventSync"
    }
  }

  if [kubernetes][container][name] == "backend" {
    mutate {
      gsub => [
        "message",
        "\u001B\[[0-9;]*[mK]",
        ""
      ]
    }

    if [message] =~ "^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS) " {
      grok {
        match => {
          "message" => '^%{WORD:[http][method]} %{URIPATHPARAM:[url][path]} %{NUMBER:[http][response][status_code]:int} %{NUMBER:[event][duration_ms]:float} ms - %{NUMBER:[http][response][body][bytes]:int}$'
        }

        tag_on_failure => [
          "_eventsync_backend_grok_failure"
        ]
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://eventsync-elasticsearch:9200"]
    index => "eventsync-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
